services:
  whoami1:
    image: traefik/whoami
    labels:
      ingress.http.routers.router-mini.Rule: PathPrefix(`/whoami`)
      ingress.http.routers.router-mini.service: service-mini
      ingress.http.services.service-mini.loadbalancer.server.port: 80
      ingress.enable: true
    deploy:
      replicas: 2
